FROM python:3.12-slim

# Install uv.
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

# Copy the application into the container.
COPY . /app

# Install the application dependencies.
WORKDIR /app
RUN uv venv
RUN uv pip install -r requirements-inference.txt

# Expose port
EXPOSE 80

# Run the application.
CMD ["/app/.venv/bin/fastapi", "run", "inference_app.py", "--port", "80", "--host", "0.0.0.0"]